version: '3.8'

services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspace
